Exit if k5start is missing

diff --git a/distributions/src/debian/init.d/continuuity-service b/distributions/src/debian/init.d/continuuity-service
--- a/distributions/src/debian/init.d/continuuity-service
+++ b/distributions/src/debian/init.d/continuuity-service
@@ -25,6 +25,13 @@ KRB_COMMAND="k5start -b -L -K 10 -p $K5PID -f $REACTOR_KEYTAB -u $REACTOR_PRINCI
 
 # check for kerberos
 if [[ -n $REACTOR_KEYTAB ]] && [[ -n $REACTOR_PRINCIPAL ]]; then
+  # Check for k5start and exit if it doesn't exist
+  if [[ $(which k5start) ]]; then
+    continue
+  else
+    echo 'Fatal: Missing k5start command! Please install k5start!'
+    exit 1
+  fi
   if [[ $1 =~ "start" ]]; then
     if [[ $UID -eq 0 ]]; then
       su continuuity -c $KRB_COMMAND
