Adding in ability to create and delete clusters

diff --git a/test-framework/regression/bin/beamer b/test-framework/regression/bin/beamer
--- a/test-framework/regression/bin/beamer
+++ b/test-framework/regression/bin/beamer
@@ -12,6 +12,7 @@ version=`cat $build_home/version.txt`
 epoch=`date +%s`
 cuser=${CINST_USER:-$USER}
 branch=`git branch | grep '*' | awk ' { print $2 } '`
+jumpbox="lm101.sw.joyent.continuuity.com"
 
 function build() {
   local component=$1; shift
@@ -82,6 +83,7 @@ function usage() {
   echo "  config       All config operations"
   echo ""
   echo "Commands for section software"
+  echo ""
   echo "  install      Install a components on the cluster from local build"
   echo "  list         List all the snapshot builds available on the cluster (*) indicates currently active"
   echo "  lock         Lock the component on the cluster."
@@ -92,15 +94,22 @@ function usage() {
   echo "  restart      Restart of all the services in a component"
   echo "  status       Status of all the services in a component"
   echo ""
-  echo "Options"
-  echo "  -c Specifies the cluster on which the command would operate on"
-  echo "  -p Specifies the package"
-  echo "  -r Specifies to use a release version (no SNAPSHOT)"
-  echo "  -t Specifies to run tests for the component locally before uploading"
+  echo "  Options"
+  echo "    -c Specifies the cluster on which the command would operate on"
+  echo "    -p Specifies the package"
+  echo "    -r Specifies to use a release version (no SNAPSHOT)"
+  echo "    -t Specifies to run tests for the component locally before uploading"
   echo ""
   echo "Commands for section config"
-  echo "  show-mapping  Shows cluster component host mapping"
+  echo ""
+  echo "  create         Create cluster"
+  echo "  destroy        Destroy cluster"
+  echo "  show-mapping   Shows cluster component host mapping"
   echo "  show-installed Shows installed components on the cluster"
+  echo ""
+  echo "  Options"
+  echo "    -c Specifies the name of the cluster"
+  echo "    -t Specifies the type of the cluster"
   echo ""
 }
 
@@ -232,6 +241,55 @@ function show_installed() {
   fi
 }
 
+function create_cluster() {
+  local cluster=$1; shift
+  local type=$1; shift
+  echo "Creating cluster $cluster of type $type (This will take approximately 10-15 minutes)"
+  ssh -oStrictHostKeyChecking=no -l $cuser $jumpbox sudo /root/run${type}cluster.sh $cuser create $cluster >/dev/null
+  echo "Install as much as you want to cluster $cluster. Host $cluster.dev.continuuity.net is accesible"
+  echo "Starting all services on cluster $cluster"
+  ssh -oStrictHostKeyChecking=no -l $cuser $cluster.dev.continuuity.net 'for i in `ls /etc/init.d/ | grep continuuity` ; do sudo service $i restart ; done'
+}
+
+echoerr() { 
+  echo "$@" 1>&2; 
+}
+
+function destroy_cluster() {
+  local cluster=$1; shift
+  local type=$1; shift
+  echo "Destroying cluster $cluster of type $type"
+  ssh -oStrictHostKeyChecking=no -l $cuser $jumpbox sudo /root/run${type}cluster.sh $cuser delete $cluster
+}
+
+function list_clusters() {
+  local type=$1; shift
+  c=0
+  for cluster in `ssh -oStrictHostKeyChecking=no -l $cuser $jumpbox sudo /root/run${type}cluster.sh A list B | grep $cuser | grep create | sed 's/ /%/g'`
+  do 
+     c=1
+     echo $cluster | awk -F"%" ' { print $3 } '
+  done
+
+  if [[ "x${c}" == "x0" ]]; then
+    echo "No clusters for user $cuser"
+  fi
+}
+
+function activity_log() {
+  local type=$1; shift
+  local c=1
+  echoerr "Activity log of all creations & deletions of ${type} clusters"
+  for line in `ssh -oStrictHostKeyChecking=no -l $cuser $jumpbox sudo /root/run${type}cluster.sh A list B | sed 's/ /%/g'`
+  do
+    local user=`echo $line | awk -F"%" ' { print $1 } '`
+    local action=`echo $line | awk -F"%" ' { print $2 }'`
+    local cluster=`echo $line | awk -F"%" ' { print $3}'`
+    printf "%03d %10s %10s %20s\n" $c $user $action $cluster
+    ((c++))
+  done
+}
+
 section=$1; shift
 
 if [[ "x${section}" == "xsoftware" ]]; then
@@ -300,23 +358,38 @@ if [[ "x${section}" == "xcluster" ]]; then
   cmd=$1; shift
 
   cluster=
+  type=
   while [ $# -gt 0 ]
   do
      case "$1" in
        -c) shift; cluster=$1; shift;;
+       -t) shift; type=$1; shift;;
        *)  usage; exit 1
      esac
   done
 
-  if [[ "x${cluster}" == "x" ]]; then
+  if [[ "x${cluster}" == "x" ]] && [[ "x${cmd}" != "xlist" ]] && [[ "x${cmd}" != "xactivity" ]]; then
     echo "Cluster not specified. Please use -c option"
     usage
+    exit -1
+  fi
+
+  if [[ "x${type}" == "x" ]]; then
+    type="dev"
+  fi
+
+  if [[ "x${type}" != "xdev" ]]; then
+    echo "Invalid type specified. Only 'dev' is currently supported"
     exit -1
   fi
 
   case "$cmd" in
     show-mapping) map $cluster;;
     show-installed) show_installed $cluster;;
+    create) create_cluster $cluster $type;;
+    destroy) destroy_cluster $cluster $type;;
+    list) list_clusters $type;;
+    activity) activity_log $type;;
   esac
   exit 0
 fi
