based on feedback

diff --git a/test-framework/performance/bin/upload-lib b/test-framework/performance/bin/upload-lib
--- a/test-framework/performance/bin/upload-lib
+++ b/test-framework/performance/bin/upload-lib
@@ -16,7 +16,7 @@ fi
 
 for host in $*
 do
-  if ! eval "ping -c 1 $host"
+  if ! eval "ping -c 1 $host >/dev/null 2>/dev/null"
   then
     echo "ERROR: Host $host is not responding."
     echo "Usage: upload-lib <host> [ <host> ... ]  "
@@ -33,7 +33,6 @@ REMOTEDIRS=''
 
 for REACTOR_COMPONENT in $REACTOR_COMPONENTS ;
 do
-  echo $REACTOR_PROJECT
   LOCALDIRS+=${REACTOR_COMPONENT}'/build/libs '
   JARPATTERNS+=${REACTOR_COMPONENT}'-?.?.?*.jar '
   REMOTEDIRS+=${REMOTE_CONTINUUITY_ROOT}/${REACTOR_COMPONENT}'/lib '
@@ -42,22 +41,26 @@ done
 for LOCALDIR in $LOCALDIRS ;
 do
   if [[ ! -d $LOCALDIR ]]; then
-    echo "ERROR: Local build directory $LOCALDIR is missing. Please change the current directory to the
-    echo         root directory of the Reactor source tree (i.e. /Users/mario/git/reactor)"
+    echo "ERROR: Local build directory $LOCALDIR is missing. Please change the current directory to the"
+    echo "       root directory of the Reactor source tree (i.e. /Users/mario/git/reactor) and verify that"
+    echo "       you have a full local Reactor build (i.e. by running gradlew build)"
     exit 1
   fi
 done
 
+echo ""
+echo "Creating local tar file /tmp/$TARFILENAME with all jars from local build:"
 tar czvf /tmp/$TARFILENAME $LOCALDIRS
 
-for host in $*
+for HOST in $*
 do
   echo ""
-  echo "Current node is $host"
+  echo "Current node is $HOST"
 
   echo ""
-  echo "Copying local file /tmp/$TARFILENAME to remote directory ${host}:/tmp"
-  scp /tmp/$TARFILENAME ${host}:/tmp
+  echo "Copying local file /tmp/$TARFILENAME to remote directory ${HOST}:/tmp"
+  scp /tmp/$TARFILENAME ${HOST}:/tmp >/dev/null
+
   for REMOTEDIR in $REMOTEDIRS
   do
     echo ""
@@ -69,13 +72,23 @@ do
 
     echo ""
     echo "Deleting existing versions of libraries in remote directory $REMOTEDIR"
-    ssh $host sudo -u continuuity "sh -c \"if [ -d $REMOTEDIR ] ; then cd $REMOTEDIR ; rm $JARPATTERNS ; fi\" "
+    ssh $HOST sudo -u continuuity "sh -c \"if [ -d $REMOTEDIR ] ; then cd $REMOTEDIR ; rm $JARPATTERNS ; fi\" "
     echo ""
     echo "Copying new versions of libraries from remote tar file /tmp/$TARFILENAME to remote directory $REMOTEDIR"
-    ssh $host sudo -u continuuity "sh -c \"if [ -d $REMOTEDIR ] ; then cd $REMOTEDIR ; tar xzvf /tmp/$TARFILENAME \
+    ssh $HOST sudo -u continuuity "sh -c \"if [ -d $REMOTEDIR ] ; then cd $REMOTEDIR ; tar xzvf /tmp/$TARFILENAME \
                                            --strip-components 3 -C $REMOTEDIR ; fi \" "
+    echo ""
+    echo "Deleting existing versions of libraries in remote directory $REMOTEDIR"
+    ssh $HOST sudo -u continuuity "sh -c \"if [ -d $REMOTEDIR ] ; then cd $REMOTEDIR ; rm $JARPATTERNS ; fi\" "
   done
+  echo ""
+  echo "Deleting remote tar file /tmp/$TARFILENAME"
+  ssh $HOST "sh -c \"if [ -f /tmp/$TARFILENAME ] ; then rm /tmp/$TARFILENAME ; fi\" "
 done
+
+echo ""
+echo "Deleting local tar file /tmp/$TARFILENAME"
+rm /tmp/$TARFILENAME
 
 echo ''
 echo '*****************************************************************************************************************'
