CDAP-4566 separate startup checks and run by init scripts
Moving startup checks from MasterServiceMain to its own class so
that they are run in a separate command. This is so we can call
it separately in the init script. This will make it so that a
startup failure will cause the init scripts to exit with a failure,
rather than having the scripts exist with a success, then have the
master fail soon after.

diff --git a/cdap-common/bin/service b/cdap-common/bin/service
--- a/cdap-common/bin/service
+++ b/cdap-common/bin/service
@@ -103,6 +103,10 @@ _start_java() {
     cdap_set_hbase || exit 1
     # Master requires this local directory
     cdap_check_or_create_master_local_dir || die "Could not create Master local directory"
+    "${JAVA}" "${JAVA_HEAPMAX}" -Dhive.classpath=${HIVE_CLASSPATH} ${OPTS} -cp ${CLASSPATH} co.cask.cdap.master.startup.MasterStartupTool </dev/null >>${loglog} 2>&1
+    if [ $? -ne 0 ]; then
+      die "Master startup checks failed. Please check ${loglog} to address issues."
+    fi
   fi
   cdap_check_before_start || exit 1
   cdap_create_pid_dir || die "Could not create PID dir: ${PID_DIR}"
