ENG-2986 Adding in LICENSE-2.0.txt to package

diff --git a/singlenode/bin/continuuity-reactor b/singlenode/bin/continuuity-reactor
--- a/singlenode/bin/continuuity-reactor
+++ b/singlenode/bin/continuuity-reactor
@@ -95,7 +95,12 @@ check_before_start() {
 
   # Checks if nodejs is available before it starts reactor.
   command -v node >/dev/null 2>&1 || \
-    { echo >&2 "continuuity-reactor requires nodeJS but it's either not installed or not in path.  Aborting."; exit 1; }
+    { echo >&2 "Continuuity Reactor requires nodeJS but it's either not installed or not in path.  Aborting."; exit 1; }
+
+  # Check if node JS is running
+  exec 6<>/dev/tcp/localhost/9999 && {     }
+  exec 6>&- # close output connection
+  exec 6<&- # close input connection
 
   if [ -f $pid ]; then
     if kill -0 `cat $pid` > /dev/null 2>&1; then
