Program and version checks - java/node

diff --git a/singlenode/bin/continuuity-reactor b/singlenode/bin/continuuity-reactor
--- a/singlenode/bin/continuuity-reactor
+++ b/singlenode/bin/continuuity-reactor
@@ -22,6 +22,17 @@ WEB_APP_PATH=${WEB_APP_PATH:-"web-app/local/server/main.js"}
 APP_NAME="continuuity-reactor"
 APP_BASE_NAME=`basename "$0"`
 
+
+function program_is_installed {
+  # set to 0 initially
+  local return_=0
+  # set to 0 if not found
+  type $1 >/dev/null 2>&1 || { local return_=1; }
+  # return value
+  echo "$return_"
+}
+
+
 warn ( ) {
     echo "$*"
 }
@@ -72,6 +83,28 @@ else
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
+fi
+
+# java version check
+JAVA_VERSION=`java -version 2>&1 | grep "java version" | awk '{print $3}' | awk -F '.' '{print $2}'`
+if [ $JAVA_VERSION -ne 6 ]; then
+  die "ERROR: Java version not supported
+Please install Java 6 - other versions of Java are not supported."
+fi
+
+# Check node installation
+NODE_INSTALL_STATUS=$(program_is_installed node)
+if [ "x$NODE_INSTALL_STATUS" == "x1" ]; then
+  die "Node.js is not installed  
+Please install Node.js - the minimum version supported v0.10.20."
+fi
+
+# Check node version
+NODE_VERSION_MAJOR=`node -v 2>&1 | awk -F '.' '{print $2}'`
+NODE_VERSION_MINOR=`node -v 2>&1 | awk -F '.' '{print $3}'`
+if [ $NODE_VERSION_MAJOR -lt 10 ] || [ $NODE_VERSION_MINOR -lt 20 ]; then
+  die "ERROR: node version is not supported
+The minimum version supported is v0.10.20." 
 fi
 
 
